project:
  type: book
  output-dir: docs

book:
  title: "PromptCraft"
  author: "RA Stringer"
  search: true
  repo-url: https://github.com/rastringer/promptcraft
  sharing: [twitter]
  chapters:
    - index.qmd
    - prompting_and_verification.ipynb
    - chain_of_thought.ipynb
    - chaining_prompts.ipynb
    - evaluation.ipynb
    - day_1_exercise.ipynb
    - langchain_intro.ipynb
    - a_new_hope.ipynb
    - product_retrieval_llms_embeddings.ipynb
    - day_2_exercise.ipynb
    - day_3_hackathon.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



