project:
  type: book
  output-dir: docs

book:
  title: "PromptCraft"
  author: "RA Stringer"
  search: true
  repo-url: https://github.com/rastringer/promptcraft
  sharing: [twitter]
  chapters:
    - index.qmd
    - part: "Day One"
      chapters:
      - prompting_and_verification.ipynb
      - chain_of_thought.ipynb
      - chaining_prompts.ipynb
      - evaluation.ipynb
      - day_1_exercise.ipynb
    - part: "Day Two"
      chapters:
      - langchain_intro.ipynb
      - langchain_memory.ipynb
      - langchain_chains.ipynb
      - agents_vectorstores.ipynb
      - enterprise_search.ipynb
      - a_new_hope.ipynb
      - product_retrieval_llms_embeddings.ipynb
      - day_2_exercise.ipynb
    - part: "Day Three"
      chapters:
      - day_3_hackathon.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



