project:
  type: book
  output-dir: docs

book:
  title: "PromptCraft"
  author: "RA Stringer"
  search: true
  repo-url: https://github.com/rastringer/promptcraft
  cover-image: logo2.jpeg
  chapters:
    - index.qmd
    - part: "The LLM Toolkit"
      chapters:
      - prompting_and_verification.ipynb
      - chaining_prompts.ipynb
      - evaluation.ipynb
      - part_1_exercise.ipynb
    - part: "LangChain"
      chapters:
      - langchain_intro.ipynb
      - langchain_memory.ipynb
      - langchain_chains.ipynb
      - agents_vectorstores.ipynb
    - part: "Semantic Exploration and Adaption"
      chapters:
      - enterprise_search.ipynb
      - a_new_hope.ipynb
      - product_retrieval_llms_embeddings.ipynb
      - fine_tuning.ipynb
      - part_3_exercise.ipynb
    - part: "Hackathon"
      chapters:
      - part_4_hackathon.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cerulean
  pdf:
    documentclass: scrreprt



